version: '3.8'
services:
  php:
    build: .

    # https://serversideup.net/open-source/docker-php/docs/reference/environment-variable-specification
    environment:
      SSL_MODE: 'off'
      PHP_OPCACHE_ENABLE: '1'
      PHP_MEMORY_LIMIT: '512M'
      PHP_MAX_EXECUTION_TIME: '300'

    # https://docs.dokploy.com/docs/core/troubleshooting#docker-compose-domain-not-working
    # let the docker generate random port for the host to use when we deploy to dokploy
    ports:
      - 8080
